### ISSUE TITLE
Versioning of datasets

### ISSUE THREAD

**Issue by bjonnh** [w3c/hcls-natural-product-drug-interaction-fair#9]
We do not seem to talk about versioning. What should be the recommendation here?

The way it is handled on zenodo for example is that each dataset version gets a DOI, and each of them allow to see the full version history (past and future of that specific version) see a random example here: https://zenodo.org/record/3547224

This is particularly useful for merged datasets that combine resources from several other datasets which will evolve independently.

**Comment by ericprud** [comment]
You can suggest the use of [prov](https://www.w3.org/TR/prov-primer/) and [pav](https://pav-ontology.github.io/pav/). The image at the bottom of the introduction in \[pav] is pretty informative. It's small, but it's SVG so you can zoom the heck out of it without producing fatbits.

A couple key properties are `prov:wasDerivedFrom` and `pav:derivedFrom` (use the latter if additional knowledge was added or derived).

**Comment by rkboyce** [comment]
Great comment and reply. I changed the recommendation "Make the update frequency of data explicit"  to say "Make the data update frequency and versioning information explicit". I then point the reader to the recommendations "Provide Data Up to Date" and "Best Practices for Data Versioning" in the W3C report "Data on the Web Best Practices". It think this is a good approach because it provides rich details and examples that we don't need to reinvent in our guide.
